version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@0.1.0

commands:
  run-test: plugin-ci/test

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
    - "/go/pkg/mod"

jobs:
  
  test:
    environment: 
      GOTESTSUM_JUNITFILE: /tmp/test-results/gotestsum.xml # path to where test result will be saved
    executor: plugin-ci/default
    steps:
      - checkout
      - run: mkdir -p /tmp/test-results/ # create the test results directory
      - *restore_cache
      - run: make test
      - *save_cache
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
              path: /tmp/test-results/
  lint:
    executor:
      name: plugin-ci/default
    environment:
      LINT_DIRECTORY: /tmp/lint-results/
    steps:
      - checkout
      - plugin-ci/install-golangci-lint
      - run: mkdir -p $LINT_DIRECTORY
      - *restore_cache
      - run:
          name: Checking code style
          command: |
            golangci-lint run --out-format junit-xml ./... > ${LINT_DIRECTORY}/golangci-lint.xml
      - run: go mod tidy -v
      - run:
          name: Check git diff
          command: |
            git --no-pager diff --exit-code go.mod go.sum
          when: always
      - *save_cache
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: /tmp/lint-results
          destination: raw-lint-output
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
              path: /tmp/lint-results/
  

workflows:
  ci-build:
    jobs:
      - lint:
          filters:
                tags:
                  only: /^v\d+\.\d+\.\d+$/
      - test:
          filters:
              tags:
                only: /^v\d+\.\d+\.\d+$/
      - plugin-ci/build:
          requires:
            - lint
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - plugin-ci/deploy-release-github:
          requires:
            - plugin-ci/build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/